server {
    listen 80;
    server_name ibifert.duckdns.org;

    # Mantém a rota do Certbot aberta para as futuras renovações automáticas
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redireciona o tráfego HTTP normal para HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ibifert.duckdns.org;

    # Aponta para os certificados gerados pelo Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/ibifert.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ibifert.duckdns.org/privkey.pem;

    # Serve o Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redireciona chamadas de API para o Backend
    location /api/ {
        proxy_pass http://backend:3000; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}