version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: pdros1812/ibiferti-backend:latest
    container_name: ibiferti-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/ibifertydb
      - JWT_SECRET=mude-isso-em-producao
    depends_on:
      - db
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: pdros1812/ibiferti-frontend:latest
    container_name: ibiferti-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: ibiferti-db-prod
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ibifertydb
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    # Opcional: expor porta se precisar acessar externamente
    # ports:
    #   - "5433:5432"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  pgdata_prod: