version: '3.8'

services:
  backend:
    image: pdros1812/ibiferti-backend:latest
    container_name: ibiferti-api
    restart: unless-stopped
    ports:
      - "3000:3000" # Confirme se o seu Node expõe a porta 3000
    environment:
      - NODE_ENV=production
      # - DB_HOST=db # Já deixando o espaço mental para quando colocar o Postgres
    
  frontend:
    image: pdros1812/ibiferti-frontend:latest
    container_name: ibiferti-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Nova porta exposta para o tráfego HTTPS
    volumes:
      # Mapeia o nginx.conf local para dentro do container (facilita a edição para o Certbot)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Volumes do Certbot para o desafio e para os certificados gerados
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    # O Certbot não precisa ficar rodando o tempo todo, ele será chamado pontualmente
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt